backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
site_url: https://macs-basic-blog.netlify.app
display_url: https://macs-basic-blog.netlify.app
logo_url: "/assets/logo.svg"
collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    #default fields for blog article
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "jumbo1"
    label: "Jumbo 1"
    folder: "src/components/jumbo1"
    slug: "{{name}}"
    fields:
      - {label: "Visibile", name: "visible", widget: "boolean", default: true}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Testo Bottone Sinistra", name: "btnsx", widget: "string"}
      - {label: "Link Bottone Sinistra", name: "btnsxLink", widget: "string"}
      - {label: "Testo Bottone Destra", name: "btndx", widget: "string"}
      - {label: "Link Bottone Destra", name: "btndxLink", widget: "string"}
  - name: "custompage"
    label: "Custom Page"
    folder: "src/pages"
    slug: "custompage"
    fields:
      - label: "Jumbo 1"
        name: "jumbo1"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Show this jumbo?", name: "visible", widget: "select", options: [{ label: "Show", value: "show" }, { label: "Hide", value: "d-none" }]}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Description", name: "imageAlt", widget: "string"}
          - {label: "Testo Bottone Sinistra", name: "btnsx", widget: "string"}
          - {label: "Link Bottone Sinistra", name: "btnsxLink", widget: "string"}
          - {label: "Testo Bottone Destra", name: "btndx", widget: "string"}
          - {label: "Link Bottone Destra", name: "btndxLink", widget: "string"}
      - label: "Jumbo 2"
        name: "jumbo2"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Show this jumbo?", name: "visible", widget: "select", options: [{ label: "Show", value: "show" }, { label: "Hide", value: "d-none" }]}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Testo Bottone Sinistra", name: "btnsx", widget: "string"}
          - {label: "Link Bottone Sinistra", name: "btnsxLink", widget: "string"}
          - {label: "Testo Bottone Destra", name: "btndx", widget: "string"}
          - {label: "Link Bottone Destra", name: "btndxLink", widget: "string"}
      - label: "Jumbo 3"
        name: "jumbo3"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Show this jumbo?", name: "visible", widget: "select", options: [{ label: "Show", value: "show" }, { label: "Hide", value: "d-none" }]}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Description", name: "imageAlt", widget: "string"}
          - {label: "Testo Bottone Sinistra", name: "btnsx", widget: "string"}
          - {label: "Link Bottone Sinistra", name: "btnsxLink", widget: "string"}
          - {label: "Testo Bottone Destra", name: "btndx", widget: "string"}
          - {label: "Link Bottone Destra", name: "btndxLink", widget: "string"}
