backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
site_url: https://macs-basic-blog.netlify.app
display_url: https://macs-basic-blog.netlify.app
logo_url: "/assets/logo.svg"
collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    #default fields for blog article
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}