backend:
  name: git-gateway
  branch: master
media_folder: "public/assets"
public_folder: "/assets"
site_url: massimo-piazza-lite.netlify.app
display_url: massimo-piazza-lite.netlify.app
logo_url: "/assets/logo.svg"
collections: 
  - name: "activities"
    label: "Intro Activities"
    folder: "src/activities"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    #default fields for blog article
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["activities"]}
  - name: "jobs"
    label: "Jobs"
    folder: "src/jobs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{company}}"
    #default fields for blog article
    fields:
      - {label: "Profession", name: "profession", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Suffix", name: "suffix", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Target", name: "target", widget: "select", options: ["_target", "_self"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "starting-date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["jobs"]}
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    #default fields for blog article
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "File", name: "file", widget: "file", default: '-'}
      - {label: "Link", name: "link", widget: "string", default: '-'}
      - {label: "Date", name: "starting-date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["projects"]}